version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/tata-webhook

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/restart_service.sh
      timeout: 300